const $=id=>document.getElementById(id),token=document.querySelector('meta[name=session-token]').content;
let pending=false,lastState='',signal=[],lastPulse=-1;
async function api(route,data){const r=await fetch('/api/'+route,{method:data===undefined?'GET':'POST',headers:{'X-Session-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw new Error(v.error??r.statusText);return v;}
function error(e){$('error').hidden=false;$('error').textContent=e.message;}
async function action(fn){if(pending)return;pending=true;$('error').hidden=true;try{await fn();}catch(e){error(e);}finally{pending=false;await poll();}}
function configuration(){const f=new FormData($('setup'));return {cameraCount:Number(f.get('cameraCount')),fps:Number(f.get('fps')),durationSeconds:f.has('manual')?null:Number(f.get('durationSeconds')),scenario:f.get('scenario'),cameras:Array.from({length:Number(f.get('cameraCount'))},(_,i)=>({id:`SIM_${i+1}`,serial:'',width:Number(f.get('width')),height:Number(f.get('height')),pixelFormat:f.get('pixelFormat')}))};}
function budget(){const c=configuration(),rate=c.cameras[0].width*c.cameras[0].height*(c.cameras[0].pixelFormat==='Mono16'?2:1)*c.fps*c.cameraCount;$('budget').textContent=`Raw budget: ${(rate/1e6).toFixed(2)} MB/s · ${c.durationSeconds===null?'manual duration':(rate*c.durationSeconds/1e9).toFixed(3)+' GB'} before reserve`;} $('setup').addEventListener('input',budget);budget();
$('setup').addEventListener('submit',e=>{e.preventDefault();action(async()=>{await api('configure',configuration());});});
for(const op of ['precheck','arm','start','stop'])$(op).onclick=()=>action(()=>api(op,{}));
$('tdt').onclick=()=>action(async()=>{$('tdtStatus').textContent=JSON.stringify(await api('tdt-status'),null,2);});
$('realStart').onclick=()=>action(async()=>{await api('real/start',{serials:$('realSerial').value.trim().split(/[,\s]+/),fps:Number($('realFps').value),seconds:Number($('realSeconds').value)});});
$('realStop').onclick=()=>action(()=>api('real/stop',{}));
let cameraSnapshot=null;
const parameterLabels={ExposureAuto:'Automatic exposure',ExposureTime:'Exposure time (µs)',GainAuto:'Automatic gain',Gain:'Gain (camera units)',Width:'ROI width',Height:'ROI height',OffsetX:'ROI X offset',OffsetY:'ROI Y offset',PixelFormat:'Pixel format'};
function showCameraParameters(r){cameraSnapshot=r;const list=[];for(const [key,label] of Object.entries(parameterLabels)){const info=r.fields[key];if(!info)continue;const wrapper=document.createElement('label');wrapper.textContent=label;const input=document.createElement(info.choices?'select':'input');input.dataset.parameter=key;if(info.choices){input.replaceChildren(...info.choices.map(v=>new Option(v,v)));if(!info.choices.includes(info.value))input.append(new Option(info.value,info.value));}else{input.type='number';input.min=info.min;input.max=info.max;input.step=info.step??'any';}input.value=info.value;input.disabled=!info.writable;wrapper.append(input);list.push(wrapper);} $('parameterInputs').replaceChildren(...list);$('cameraFields').disabled=false;showCameraRate();}
function showCameraRate(){if(!cameraSnapshot)return;const f=cameraSnapshot.fields,rate=f.ResultingFrameRate?.value,target=Number($('realFps').value);$('cameraSettingsStatus').textContent=`Camera ${cameraSnapshot.serial}\nExposure: ${f.ExposureTime?.value??'unavailable'} µs\nEstimated rate for current settings: ${rate??'unavailable'} fps\nCamera frame-rate limit: ${f.AcquisitionFrameRateEnable?.value?'enabled':'disabled'}, set to ${f.AcquisitionFrameRate?.value??'unavailable'} fps\n${Number.isFinite(rate)&&rate<target?'The estimated rate is below the study target. Check exposure, ROI, and the frame-rate limit.':'The requested rate will be checked again when the study starts.'}`;}
async function settingsCall(data){try{return await api('camera/settings',data);}catch(e){$('cameraSettingsStatus').textContent=e.message;throw e;}}
$('discoverCameras').onclick=()=>action(async()=>{const r=await settingsCall({operation:'list'});cameraSnapshot=null;$('cameraFields').disabled=true;$('parameterInputs').replaceChildren();$('settingsCamera').replaceChildren(new Option('Select a camera',''),...r.devices.map(d=>new Option(`${d.serial} · ${d.model}`,d.serial)));});
$('settingsCamera').onchange=()=>{cameraSnapshot=null;$('cameraFields').disabled=true;$('parameterInputs').replaceChildren();$('cameraSettingsStatus').textContent='Click Read settings.';};
$('readCamera').onclick=()=>action(async()=>{showCameraParameters(await settingsCall({operation:'read',serial:$('settingsCamera').value}));});
$('applyCamera').onclick=()=>action(async()=>{if(!cameraSnapshot||cameraSnapshot.serial!==$('settingsCamera').value)throw Error('Read the selected camera settings first.');const changes={};for(const input of $('parameterInputs').querySelectorAll('[data-parameter]')){const key=input.dataset.parameter,info=cameraSnapshot.fields[key],value=info.choices?input.value:Number(input.value);if(!input.disabled&&value!==info.value)changes[key]=value;}if(!Object.keys(changes).length){$('cameraSettingsStatus').textContent='No settings changed.';return;}showCameraParameters(await settingsCall({operation:'apply',serial:cameraSnapshot.serial,changes}));});
$('realFps').addEventListener('input',showCameraRate);
function drawReal(canvas,p){canvas.width=p.width;canvas.height=p.height;const ctx=canvas.getContext('2d'),im=ctx.createImageData(p.width,p.height),bytes=atob(p.data);for(let i=0;i<p.width*p.height;i++)im.data.set([bytes.charCodeAt(i*3),bytes.charCodeAt(i*3+1),bytes.charCodeAt(i*3+2),255],i*4);ctx.putImageData(im,0,0);}
async function realRecordings(){const old=$('realRecordings').value,list=await api('real/recordings');$('realRecordings').replaceChildren(new Option('Select a real recording',''),...list.map(r=>new Option(`${r.serial} · ${r.state} · ${r.id.split('/').at(-1)}`,r.id)));if(list.some(r=>r.id===old))$('realRecordings').value=old;else if(list.length)$('realRecordings').value=list[0].id;}
async function realReplay(){const p=await api('real/frame?id='+encodeURIComponent($('realRecordings').value)+'&index='+encodeURIComponent($('realFrameIndex').value));drawReal($('realReplayCanvas'),p);$('realReplayCanvas').hidden=false;$('realReplayLabel').textContent=`${p.serial} · decoded saved video · frame ${p.frame_index} · ${p.display_conversion}`;}
$('realRefresh').onclick=()=>action(realRecordings);
$('realReplay').onclick=()=>action(realReplay);
$('realNext').onclick=()=>action(async()=>{$('realFrameIndex').value=Number($('realFrameIndex').value)+1;await realReplay();});
let previousRealState='',lastPreviewFrames=new Map();
async function realPreviews(real){const previews=await api('real/previews');const ids=previews.map(p=>p.serial).join(',');if($('realPreviews').dataset.ids!==ids){$('realPreviews').dataset.ids=ids;lastPreviewFrames.clear();$('realPreviews').replaceChildren(...previews.map(p=>{const article=document.createElement('article');article.className='camera';const title=document.createElement('h3');title.textContent=p.serial+' · REAL';const canvas=document.createElement('canvas');canvas.id='realCanvas-'+p.serial;const label=document.createElement('p');label.id='realLabel-'+p.serial;article.append(title,canvas,label);return article;}));}for(const p of previews){if(lastPreviewFrames.get(p.serial)!==p.frame_index){drawReal($('realCanvas-'+p.serial),p);lastPreviewFrames.set(p.serial,p.frame_index);}$('realLabel-'+p.serial).textContent=`${p.active?'live preview':'stopped · last preview'} · frame ${p.frame_index} · ${p.updated_utc}`;}if(real.state!==previousRealState&&['COMPLETE','FAULT'].includes(real.state))await realRecordings();previousRealState=real.state;}
async function sessions(){const old=$('sessions').value;const list=await api('sessions');$('sessions').replaceChildren(new Option('Select a session',''),...list.map(s=>new Option(`${s.state} · ${s.id}`,s.id)));if(list.some(s=>s.id===old))$('sessions').value=old;}
$('refresh').onclick=()=>action(sessions);
$('review').onclick=()=>action(async()=>{const r=await api('review?id='+encodeURIComponent($('sessions').value));$('report').textContent=JSON.stringify(r.qc??r.manifest,null,2);$('segments').replaceChildren(...(r.qc?.segments??[]).map(s=>new Option(`${s.file} · ${s.verified?'verified':'partial'}`,s.file)));});
$('audit').onclick=()=>action(async()=>{$('report').textContent=JSON.stringify(await api('audit',{id:$('sessions').value}),null,2);});
$('replay').onclick=()=>action(async()=>{const r=await api('frame?id='+encodeURIComponent($('sessions').value)+'&file='+encodeURIComponent($('segments').value)+'&index='+encodeURIComponent($('frameIndex').value));$('replayImage').src='data:image/png;base64,'+r.png;$('replayImage').hidden=false;});
$('attach').onclick=()=>action(async()=>{const file=$('ttlFile').files[0];if(!file)throw new Error('Select a TTL CSV');const r=await api('attach-tdt',{id:$('sessions').value,nativeBlockPath:$('nativePath').value,operator:$('operator').value,ttlCSV:await file.text()});$('report').textContent=JSON.stringify(r,null,2);});
async function poll(){try{
  const real=await api('real/status'),realBusy=['RUNNING','STOPPING'].includes(real.state);$('realStatus').textContent=JSON.stringify(real.report??real,null,2);$('realStart').disabled=pending||realBusy;$('realStop').disabled=pending||!realBusy;
  await realPreviews(real);$('realReplay').disabled=pending||realBusy;$('realNext').disabled=pending||realBusy;
  const s=await api('status'),state=s.state;$('state').textContent=state;$('pulses').textContent=s.generated_pulses??0;$('elapsed').textContent=(s.elapsed_wall_s??0).toFixed(1)+' s';$('free').textContent=s.free_bytes===undefined?'—':(s.free_bytes/1e9).toFixed(1)+' GB';
  $('realStart').disabled=pending||realBusy||['RECORDING','FINALIZING'].includes(state);
  const parametersBusy=pending||realBusy||['RECORDING','FINALIZING'].includes(state);for(const id of ['discoverCameras','readCamera','settingsCamera'])$(id).disabled=parametersBusy;$('cameraFields').disabled=parametersBusy||!cameraSnapshot;
  for(const [id,enabled]of [['precheck',state==='CONFIGURED'],['arm',state==='PRECHECKED'],['start',state==='ARMED'],['stop',state==='RECORDING'],['configure',!['RECORDING','FINALIZING'].includes(state)]])$(id).disabled=pending||realBusy||!enabled;
  if(s.faults?.length)error(new Error(s.faults.map(f=>f.message).join('\n')));
  const ids=s.config?.cameras.map(c=>c.id)??[];if($('cameras').dataset.ids!==ids.join(',')){$('cameras').dataset.ids=ids.join(',');$('cameras').replaceChildren(...ids.map(id=>{const el=document.createElement('article');el.className='camera';const h=document.createElement('h3');h.textContent=id+' · SIMULATED';const canvas=document.createElement('canvas');canvas.id='canvas-'+id;const p=document.createElement('p');p.id='stats-'+id;el.append(h,canvas,p);return el;}));signal=[];lastPulse=-1;}
  for(const id of ids){const p=s.preview?.[id],stats=s.streams?.[id];if(p){const c=$('canvas-'+id);c.width=p.width;c.height=p.height;c.title=p.label;const ctx=c.getContext('2d'),image=ctx.createImageData(p.width,p.height),bytes=atob(p.data),channels=p.channels??1;for(let i=0;i<p.width*p.height;i++){const n=i*channels,v=bytes.charCodeAt(n);image.data.set(channels===3?[v,bytes.charCodeAt(n+1),bytes.charCodeAt(n+2),255]:[v,v,v,255],i*4);}ctx.putImageData(image,0,0);}const t=s.capture_elapsed_s||1;$('stats-'+id).textContent=stats?`Received ${stats.received} · submitted ${stats.encoder_submitted} · pending ${stats.pending} / ${s.config.queueFrames} · mean receive ${(stats.received/t).toFixed(1)} fps · mean submit ${(stats.encoder_submitted/t).toFixed(1)} fps`:'Waiting for recording';}
  if(s.neural_preview&&s.generated_pulses!==lastPulse){lastPulse=s.generated_pulses;signal.push(s.neural_preview.value);if(signal.length>200)signal.shift();const c=$('neural'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#70dfbf';ctx.beginPath();signal.forEach((v,i)=>{const x=i*c.width/200,y=c.height/2-v*35;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}
  if(state!==lastState&&['COMPLETE','FAULT'].includes(state)){await sessions();if(s.report)$('report').textContent=JSON.stringify(s.report,null,2);}lastState=state;
}catch(e){error(e);}}
async function loop(){await poll();setTimeout(loop,100);}sessions().catch(error);loop();
realRecordings().catch(error);
